# Config file for GFlows.
# See https://github.com/jbrunton/gflows/wiki/Configuration for options.
githubDir: ../../.github
templates:
  engine: ytt
  defaults:
    dependencies:
    - https://raw.githubusercontent.com/jbrunton/gflows/separate-libs-packages/e2e/gflowslibs/ytt
